# Generated by Django 4.2.11 on 2024-04-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0011_remove_phong_gia10h_19h_remove_phong_gia14h_12h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trangchu.phong')),
            ],
        ),
    ]
