# Generated by Django 4.2.11 on 2024-04-29 17:58

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0012_image_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_room',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_5',
            field=models.ImageField(blank=True, null=True,  upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_7',
            field=models.ImageField(blank=True, null=True,  upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_room',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
