# Generated by Django 4.2.11 on 2024-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0013_alter_image_room_image_1_alter_image_room_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='Diachi_cuthe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
