# Generated by Django 4.2.11 on 2024-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0014_phong_diachi_cuthe'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='Gia4tieng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
