# Generated by Django 4.2.11 on 2024-05-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0015_phong_gia4tieng'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='Gia10h_19h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia14h_12h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='Gia20h_9h',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
