# Generated by Django 4.2.11 on 2024-05-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0016_phong_gia10h_19h_phong_gia14h_12h_phong_gia20h_9h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang_items',
            name='giohang',
        ),
        migrations.RemoveField(
            model_name='giohang_items',
            name='phong',
        ),
        migrations.DeleteModel(
            name='Banggia',
        ),
        migrations.DeleteModel(
            name='Giohang',
        ),
        migrations.DeleteModel(
            name='Giohang_items',
        ),
    ]
