# Generated by Django 4.2.11 on 2024-05-04 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0019_remove_phong_diachi_cuthe'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_room',
            name='phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trangchu.phong'),
        ),
    ]
