# Generated by Django 4.2.11 on 2024-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0020_image_room_phong'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_imgae', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='phong',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='map',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='tiktokvid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
