# Generated by Django 4.2.11 on 2024-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0021_posts_phong_description_phong_map_phong_tiktokvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='map',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='tiktokvid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
