# Generated by Django 4.2.11 on 2024-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0022_alter_phong_map_alter_phong_tiktokvid'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Room Booked',
            },
        ),
        migrations.AlterField(
            model_name='phong',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
