# Generated by Django 5.0.4 on 2024-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0026_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia10h_19h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia14h_12h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia20h_9h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='Gia4tieng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
