# Generated by Django 4.2.11 on 2024-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0027_alter_order_item_price_alter_phong_gia10h_19h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
