# Generated by Django 4.2.11 on 2024-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0028_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
