# Generated by Django 4.2.11 on 2024-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0029_alter_order_item_checkin_alter_order_item_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
